name: deploy to cloudflare workers
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup rustup
        run: |
          curl https://sh.rustup.rs -sSf | bash -s -- -y
          source "$HOME/.cargo/env"

      - name: cloudflare workers publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            TELEGRAM_API_TOKEN
        env:
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
